### ISSUE TITLE
Exposure of sensitive token in crowdin.yml poses security risk

### ISSUE THREAD

**Issue by rhyme-qing** [Jiangxue-team/qionglou#3]
I have identified a security concern in our project where the crowdin.yml file contains a sensitive token. This token grants access to our Crowdin localization platform. Unfortunately, the file was mistakenly committed to our GitHub repository, making the token accessible to unauthorized individuals.

```yml
'project_id': '584693'
'api_token': 'eyJ……'
'base_path': '.'
'base_url': 'https://api.crowdin.com'
```

Please @XiaoLi-sach re-or delete the api_token of crowdin to avoid some problems.
